export default {
    0: "CubicMeter",
    1: "SquareMeter",
    2: "Meter",
    3: "SquareCentimeter",
    4: "Centimeter",
    5: "Set",
    6: "Unit",
    7: "Part",
    8: "Bag",
    9: "Kilogram",
    10: "Liter",
    11: "Barrel",
    12: "Frame",
    13: "Roll",
    14: "Thread",
    15: "Label",
    16: "Node",
    17: "Bar",
    18: "Box",
    19: "Sheet",
    20: "TransportationUnit",
    21: "Worker",
    22: "Kilometer",
    23: "Modun",
    24: "Unclassified",
    25: "Shelf",
};
