const calculationUnitOptions = [
    "m3",
    "m²",
    "m",
    "cm²",
    "cm",
    "Bộ",
    "Cái",
    "Phần",
    "Túi",
    "Kg",
    "l",
    "Thùng",
    "Frame",
    "Roll",
    "Thread",
    "Nhãn",
    "Node",
    "Thanh",
    "Hộp",
    "Tấm",
    "Đơn vị vận chuyển",
    "Người",
    "Km",
    "Modun",
    "Không xác định",
    "Kệ",
  ];
  const calculationUnitOptionsEnglish = [
    "CubicMeter",
    "SquareMeter",
    "Meter",
    "SquareCentimeter",
    "Centimeter",
    "Set",
    "Unit",
    "Part",
    "Bag",
    "Kilogram",
    "Liter",
    "Barrel",
    "Frame",
    "Roll",
    "Thread",
    "Label",
    "Node",
    "Bar",
    "Box",
    "Sheet",
    "TransportationUnit",
    "Worker",
    "Kilometer",
    "Modun",
    "Unclassified",
    "Shelf",
  ];
  const calculationUnitIndex = {
    CubicMeter: 0,
    SquareMeter: 1,
    Meter: 2,
    SquareCentimeter: 3,
    Centimeter: 4,
    Set: 5,
    Unit: 6,
    Part: 7,
    Bag: 8,
    Kilogram: 9,
    Liter: 10,
    Barrel: 11,
    Frame: 12,
    Roll: 13,
    Thread: 14,
    Label: 15,
    Node: 16,
    Bar: 17,
    Box: 18,
    Sheet: 19,
    TransportationUnit: 20,
    Worker: 21,
    Kilometer: 22,
    Modun: 23,
    Unclassified: 24,
    Shelf: 25,
  };
  export { calculationUnitOptionsEnglish, calculationUnitIndex };
  export default calculationUnitOptions;
  